//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBAIBCCI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Matchwinsoft
    {
        public int MatchId { get; set; }
        public int SeriesId { get; set; }
        public string MatchName { get; set; }
        public System.DateTime MatchDate { get; set; }
    
        public virtual Serieswinsoft Serieswinsoft { get; set; }
    }
}
